name: Deploy to Google Cloud Run

on:
  release:
    types: [created]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ vars.GCP_PROJECT_ID }}

    - name: Authenticate with Google Cloud
      run: |
        gcloud components install beta
        gcloud auth configure-docker
        
    - name: Grant Run Admin permissions
      run: |
        gcloud projects add-iam-policy-binding ${{ vars.GCP_PROJECT_ID }} \
          --member="serviceAccount:${{ vars.GCP_SA_EMAIL }}" \
          --role="roles/run.admin"

    - name: Build and push Docker image
      run: |
        docker build -t asia.gcr.io/${{ vars.GCP_PROJECT_ID }}/moony-stock-api:${{ github.sha }} .
        docker push asia.gcr.io/${{ vars.GCP_PROJECT_ID }}/moony-stock-api:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |
        gcloud beta run services add-iam-policy-binding moony-stock-api \
          --region=${{ vars.GCP_REGION }} \
          --member="allUsers" \
          --role="roles/run.invoker" \
          --quiet
        gcloud run deploy moony-stock-api \
          --image asia.gcr.io/${{ vars.GCP_PROJECT_ID }}/moony-stock-api:${{ github.sha }} \
          --platform managed \
          --region ${{ vars.GCP_REGION }} \
          --allow-unauthenticated
